// edanic-seo/edanic-ssr.mjs — Edanic 交付渲染器(Express/Connect 兼容,依赖无关)。
// 把它挂在你的 SPA 兜底路由【之前】,爬虫访问 Edanic 页时拿到服务端渲染的 HTML:
//   import { edanicSSR } from '../edanic-seo/edanic-ssr.mjs'   // 路径按你的 server 文件位置调整
//   app.use(edanicSSR())     // 命中已知 Edanic slug → 服务端渲染;否则 next() 交回你的应用
// AI 答案引擎(GPTBot/ClaudeBot/PerplexityBot)不跑 JS —— 这一步让这些页对它们可见。
import fs from 'node:fs'
import path from 'node:path'
import url from 'node:url'
const HERE = path.dirname(url.fileURLToPath(import.meta.url))
const CONTENT_DIR = path.resolve(HERE, '..', 'content')
function parseFront(raw){raw=String(raw==null?'':raw).replace(/\r\n?/g,'\n');const m=raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);if(!m)return{fm:{},body:raw};const fm={};for(const line of m[1].split('\n')){const i=line.indexOf(': ');if(i<0)continue;const k=line.slice(0,i).trim();const v=line.slice(i+2);try{fm[k]=JSON.parse(v)}catch{fm[k]=v}}return{fm,body:m[2]}}
function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function inl(s){s=esc(s);s=s.replace(/\[([^\]]+)\]\(([^)]+)\)/g,(_,t,u)=>'<a href="'+u.replace(/"/g,'&quot;')+'">'+t+'</a>');s=s.replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');s=s.replace(/`([^`]+)`/g,'<code>$1</code>');return s}
function table(rows){const cells=(r)=>r.trim().replace(/^\||\|$/g,'').split('|').map(c=>c.trim());const body=rows.filter(r=>!/^\s*\|?[\s:|-]+\|?\s*$/.test(r));if(!body.length)return'';const th=cells(body[0]).map(c=>'<th>'+inl(c)+'</th>').join('');const trs=body.slice(1).map(r=>'<tr>'+cells(r).map(c=>'<td>'+inl(c)+'</td>').join('')+'</tr>').join('');return '<div class="ea-tablewrap"><table><thead><tr>'+th+'</tr></thead><tbody>'+trs+'</tbody></table></div>'}
function mdToHtml(md){const lines=String(md||'').split('\n');const out=[];let i=0;while(i<lines.length){const l=lines[i];if(!l.trim()){i++;continue}let m;if((m=l.match(/^(#{1,3})\s+(.*)/))){out.push('<h'+m[1].length+'>'+inl(m[2])+'</h'+m[1].length+'>');i++;continue}if(l.startsWith('> ')){const b=[];while(i<lines.length&&lines[i].startsWith('> ')){b.push(inl(lines[i].slice(2)));i++}out.push('<blockquote>'+b.join(' ')+'</blockquote>');continue}if(l.trim().startsWith('|')){const rows=[];while(i<lines.length&&lines[i].trim().startsWith('|')){rows.push(lines[i]);i++}out.push(table(rows));continue}if(/^\s*[-*]\s+/.test(l)){const it=[];while(i<lines.length&&/^\s*[-*]\s+/.test(lines[i])){it.push('<li>'+inl(lines[i].replace(/^\s*[-*]\s+/,''))+'</li>');i++}out.push('<ul>'+it.join('')+'</ul>');continue}if(/^\s*\d+\.\s+/.test(l)){const it=[];while(i<lines.length&&/^\s*\d+\.\s+/.test(lines[i])){it.push('<li>'+inl(lines[i].replace(/^\s*\d+\.\s+/,''))+'</li>');i++}out.push('<ol>'+it.join('')+'</ol>');continue}const b=[];while(i<lines.length&&lines[i].trim()&&!/^(#{1,3}\s|>\s|\s*[-*]\s|\s*\d+\.\s|\|)/.test(lines[i])){b.push(inl(lines[i]));i++}out.push('<p>'+b.join(' ')+'</p>')}return out.join('\n')}
function listPages(dir){const out=[];const walk=(d)=>{let ents;try{ents=fs.readdirSync(d,{withFileTypes:true})}catch{return}for(const e of ents){const p=path.join(d,e.name);if(e.isDirectory())walk(p);else if(e.name.endsWith('.md')){try{const{fm}=parseFront(fs.readFileSync(p,'utf8'));const slug=String(fm.slug||'').replace(/\/+$/,'');if(slug.startsWith('/'))out.push({slug,file:p,fm})}catch{}}}};walk(dir);return out}
const _CSS=`main.edanic-answer{max-width:820px;margin:0 auto;padding:clamp(24px,5vw,56px) 20px;font-family:-apple-system, system-ui, 'Segoe UI', Roboto, sans-serif;line-height:1.75;color:#1f2328}.edanic-answer h1{font-size:2rem;line-height:1.2;margin:0 0 .6em}.edanic-answer h2{font-size:1.5rem;margin:1.8em 0 .5em}.edanic-answer h3{font-size:1.2rem;margin:1.4em 0 .4em}.edanic-answer p{margin:0 0 1em}.edanic-answer a{color:#b7521e;text-underline-offset:2px}.edanic-answer ul,.edanic-answer ol{margin:0 0 1em;padding-left:1.4em}.edanic-answer li{margin:.3em 0}.edanic-answer code{background:rgba(0,0,0,.05);border-radius:6px;padding:.1em .35em}.edanic-answer blockquote{margin:1em 0;padding:.4em 1em;border-left:3px solid #b7521e;opacity:.85}.edanic-answer .ea-tablewrap{overflow-x:auto;margin:1em 0}.edanic-answer table{border-collapse:collapse;width:100%;font-size:.95em}.edanic-answer th,.edanic-answer td{border:1px solid rgba(0,0,0,.12);padding:.5em .7em;text-align:left}.edanic-answer .ea-updated{margin-top:2.5em;font-size:.85em;opacity:.55}`;
function renderPage(fm,bodyHtml){const jl=Array.isArray(fm.jsonld)?fm.jsonld:(fm.jsonld?[fm.jsonld]:[]);const ld=jl.map(j=>'<script type="application/ld+json">'+JSON.stringify(j)+'</script>').join('');const upd=fm.last_updated?'<p class="ea-updated">Last updated: '+esc(fm.last_updated)+'</p>':'';const canon=fm.slug?'<link rel="canonical" href="'+esc(fm.slug)+'">':'';return '<!DOCTYPE html><html lang="'+esc(fm.lang||'en')+'"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(fm.title||'')+'</title><meta name="description" content="'+esc(fm.description||'')+'">'+canon+ld+'<style>'+_CSS+'</style></head><body><main class="edanic-answer"><article>'+bodyHtml+'</article>'+upd+'</main></body></html>'}
let _map=null;function _find(pathname){if(!_map){_map=new Map();for(const p of listPages(CONTENT_DIR))_map.set(p.slug,p)}try{const raw=decodeURIComponent(String(pathname||'').split('?')[0]);const p=raw.replace(/\/+$/,'')||'/';return _map.get(p)||null}catch(e){return null}}
// 框架无关核心:传入路径,命中 Edanic 页 → 返回完整 HTML;否则 null。任何 server 都能用(Fastify/Koa/Hono/raw http)。
export function edanicHtml(pathname){const hit=_find(pathname);if(!hit)return null;try{const{fm,body}=parseFront(fs.readFileSync(hit.file,'utf8'));return renderPage(fm,mdToHtml(body))}catch(e){return null}}
// Express / Connect:app.use(edanicSSR())
export function edanicSSR(){return function(req,res,next){if((req.method||'GET')!=='GET')return next();const html=edanicHtml(req.path||req.url||'');if(html==null)return next();res.statusCode=200;res.setHeader('Content-Type','text/html; charset=utf-8');res.end(html)}}
// Fastify:app.addHook('onRequest', edanicFastifyHook)  —— 加在 root 实例上=全局(插件里加会被封装、不生效)。命中回 HTML 短路,否则放行。
export function edanicFastifyHook(req,reply,done){if((req.method||'GET')!=='GET')return done();const html=edanicHtml(req.url||(req.raw&&req.raw.url)||'');if(html==null)return done();reply.header('Content-Type','text/html; charset=utf-8').send(html)}
// Koa:app.use(edanicKoa())
export function edanicKoa(){return async(ctx,next)=>{if((ctx.method||'GET')!=='GET')return next();const html=edanicHtml(ctx.path||ctx.url||'');if(html==null)return next();ctx.type='html';ctx.body=html}}
